### ISSUE TITLE
Driver waits forever after creating instance

### ISSUE THREAD

**Issue by talonx** [test-kitchen/kitchen-google#49] opened 2017-07-13 09:41 UTC
After invoking kitchen create with Ubuntu 14.04 LTS as the platform, ansible as the provisioner and gce as the driver, the instance gets created but the invocation gets stuck forever (until the timeout) on "Waiting for SSH service ". I was able to login to the instance separately using my private key, so not sure why kitchen-google is unable to detect it as up.

```
----> Creating <default-ubuntu-1404>...
Creating GCE instance <tk-default-ubuntu-1404-47e228> in project xxxxxxxxxx, zone us-east1-c...
Zone operation operation-1499938434804-5542fa1976920-27c00f7f-cdabf3ba created. Waiting for it to complete...
Current status: PENDING
Current status: RUNNING
Current status: DONE
Server <tk-default-ubuntu-1404-47e228> created.
Waiting for server <tk-default-ubuntu-1404-47e228> to be ready...
Waiting for SSH service on 35.196.55.247:22, retrying in 3 seconds
Waiting for SSH service on 35.196.55.247:22, retrying in 3 seconds
Waiting for SSH service on 35.196.55.247:22, retrying in 3 seconds
Waiting for SSH service on 35.196.55.247:22, retrying in 3 seconds
Waiting for SSH service on 35.196.55.247:22, retrying in 3 seconds
Waiting for SSH service on 35.196.55.247:22, retrying in 3 seconds

```

**Comment by cheeseplus** [comment] 2017-09-05 23:15
Are you still experiencing issues with this or did it end up being a configuration error?

**Comment by talonx** [comment] 2017-09-06 04:27
I did not get a chance to try this out again, moved on to other things.

**Comment by cheeseplus** [comment] 2017-09-09 03:21
Understood, just wanted to check ask since I haven't been able to reproduce.

**Comment by blbradley** [comment] 2018-03-11 08:58
I'm experiencing the same behavior! I can also SSH into instance with my private key.

**Comment by blbradley** [comment] 2018-03-11 09:23
Sorry, my issue was a configuration error.

**Comment by cheeseplus** [comment] 2018-03-11 12:26
No problem, the earlier error was almost definitely a configuration one as well so closing this out.

**Closed by cheeseplus** 2018-03-11 12:26 UTC
Labels: Feedback Requested
